### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by boricuapab** [nguyenvuducthuy/thuy_b2sd#1]
Getting this error:

![nomodulenamedpil](https://user-images.githubusercontent.com/61924816/226160427-fd4618ce-04b3-45ec-8e65-7fe60c45e86a.png)

**Comment by nguyenvuducthuy** [comment]
Did you run this

    Path\to\blender\3.4\python\bin\python.exe -m pip install Pillow
-> make sure "Path\to\blender\3.4\python\bin\python.exe" is a absolute path to python.exe file

**Comment by boricuapab** [comment]
Yep, I rang that as well.

![pillowInstalled](https://user-images.githubusercontent.com/61924816/226185349-b0226b61-1ee4-4326-a042-12bbfb323041.PNG)

**Comment by boricuapab** [comment]
Works after re-installing blender.
