### ISSUE TITLE
KeyError: 'images'

### ISSUE THREAD

**Issue by boricuapab** [nguyenvuducthuy/thuy_b2sd#2]
After successfully getting the b2sd addon installed, when I click on render I get this KeyError: 'images'

Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b2sd.py", line 121, in execute
    butils.doit(isanim              = b2sd.isRenAnim,
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b2sd.py", line 384, in doit
    run_sd([currentImgPath],
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b2sd.py", line 317, in run_sd
    img = Image.open(io.BytesIO(base64.b64decode(res["images"][0])))
KeyError: 'images'

![keyErrorImages2](https://user-images.githubusercontent.com/61924816/226190242-5852dd9c-3a44-4bba-9f05-cf8b21a984c8.png)

**Comment by nguyenvuducthuy** [comment]
can you show me you current UI of the b2sd tool?

**Comment by nguyenvuducthuy** [comment]
btw, you can join this channel for easy communication
https://discord.gg/MebZKdyGmh

**Comment by boricuapab** [comment]
Works now, issue was that I was missing the open pose model called

control_openpose-fp16
![missingOpenPoseModel](https://user-images.githubusercontent.com/61924816/226262343-e291d1ed-f640-4589-9544-a4533af923e2.PNG)

![works](https://user-images.githubusercontent.com/61924816/226262374-088a1d3d-d1b1-49fa-b8df-f2ecde4830c7.PNG)
