### ISSUE TITLE
b2sd UI Feature Requests 20230320

### ISSUE THREAD

**Issue by boricuapab** [nguyenvuducthuy/thuy_b2sd#4]
Hi, I'd like to make a few feature requests to the b2sd ui.

1) It would be great if the default value of the seed in the b2sd script could be increased to a higher value than is currently set 8888888, such as 8888888888

For example in a1111 I found this seed which gave me a nice result for a character that I wanted to see animated 3253343922

Here are a few other requests that would be awesome to have:

2) The ability to change these settings in the b2sd ui

"steps": 20,
"cfg_scale": 7,
"restore_faces": False,
"eta": 0,
"sampler_index": "DPM++ 2M Karras",

3) Also having the ability to use "Cutoff", which I aslo see is in the b2sd script, with the text and weight inputs exposed in the b2sd ui to be able to change them

4) For control net having the ability to change these settings in the b2sd ui

"model": "control_openpose-fp16 [9ca67cc5]",
"weight": 1,
"guidance_start": 0.0,
"guidance_end": 1.0,

**Comment by nguyenvuducthuy** [comment]
add in latest release
